### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by turol**
I sent you this back in 2015 via email but it seems to have gotten lost.

Various improvements and bug fixes by myself, @urkle and @knockoutgames.

### CODE REVIEW

**Comment by icculus** [comment]
Oh my gosh, this is a ton of patches!

I'm going to look these over today and probably merge.

**Comment by icculus** [comment]
Okay, I'm going to merge this and fix up the Visual Studio build.

Is this all old patches, or are you still actively using this project? If it's helpful, I can give you and @urkle, etc, write access to the repository so you can push directly.

**Comment by turol** [comment]
This is all old patches, I'm not using this at the moment so I don't need or want commit access. You'll have to ask the others separately.

**Comment by knockoutgames** [comment]
Oh wow. Thanks @turol for handling this! Had no idea anyone else got use out of the cube-mapping support. That was done specifically for Shadow Warrior.

**Pull request merged**
